-- Схема приложения
CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION CURRENT_USER;

-- Расширения
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Права на схему
GRANT USAGE ON SCHEMA app TO CURRENT_USER;
