version: "3.9"

networks:
  while_true-stack_icj-net:
    external: true   # подключаемся к общей сети с беком и postgres

services:
  mongo:
    image: mongo:7
    container_name: icj-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: admin
      TZ: Europe/Moscow
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo/initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - while_true-stack_icj-net
    healthcheck:
      test: ["CMD", "mongosh", "-u", "${MONGO_ROOT_USER}", "-p", "${MONGO_ROOT_PASS}", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20

  mongo-express:
    image: mongo-express:1
    container_name: icj-mongo-express
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASS}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASS:-admin}
    ports:
      - "${MONGO_EXPRESS_PORT:-8082}:8081"
    networks:
      - while_true-stack_icj-net

volumes:
  mongo_data:
